<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChartKit.Charting\ChartKit.Charting.csproj" />
    <ProjectReference Include="..\ChartKit.Contracts\ChartKit.Contracts.csproj" />
    <ProjectReference Include="..\ChartKit.Engine\ChartKit.Engine.csproj" />
    <ProjectReference Include="..\ChartKit.Rendering\ChartKit.Rendering.csproj" />
    <ProjectReference Include="..\ChartKit.DataSources\ChartKit.DataSources.csproj" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="2.88.8" />
  </ItemGroup>
</Project>
