<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ChartKit</RootNamespace>
    <AssemblyName>ChartKit</AssemblyName>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <OptionExplicit>On</OptionExplicit>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="2.88.8" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ChartKit.Tests" />
  </ItemGroup>
</Project>