<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ChartKit</RootNamespace>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>Off</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ChartKit.vbproj" />
  </ItemGroup>
</Project>
